### ISSUE TITLE
Should the shell command precede the Git?

### ISSUE THREAD

**Issue by ejether** [FairwindsOps/apprentice-learning-plan#2]
I was wondering if the shell commands should precede the git stuff requires shell work?

**Comment by kimschles** [comment]
That's a reasonable question, the assumption being 'shouldn't we cover shell commands before doing things in git?' 

This learning plan assumes that the new hire has some fluency with the command line, so I don't think it matters which order the lessons are in. I'll add a prerequisites section, though, that describes what we assume the person working through this plan can already do.

**Comment by ejether** [comment]
Yes, that is a better representation of what I was asking.  Sounds like a good plan.
